### ISSUE TITLE
The xml files in the nupkg fail the codesign verify despite being signed

### ISSUE THREAD

**Issue by dmonroym** [dotnet/project-system#6602]
The xml files in the nupkg fail the codesign verify despite being signed in https://github.com/dmonroym/project-system/blob/9e3cf5fe859c0f4d188412e32456f7611782cb2f/build/ci/SignToolData.json#L37

This task should be added to https://github.com/dotnet/project-system/blob/HEAD/build/ci/official.yml

```yml
- task: ms-vseng.MicroBuildShipTasks.7c429315-71ba-4cb3-94bb-f829c95f7915.MicroBuildCodesignVerify@2
  displayName: Verify Signed Files
  inputs:
    TargetFolders: |
      $(Build.SourcesDirectory)/artifacts/$(BuildConfiguration)/packages
```
